#!/bin/bash
# dbnd-release - A script to release dbnd project
usage()
{
    echo "usage: dbnd-release [patch|minor]"
}

if [[ $# -eq 0 ]] ; then
    usage
    exit 1
fi

##### Constants
VERSION_TYPE=$1
NEW_DBND_VERSION=$(bumpversion $VERSION_TYPE --dry --list | grep new_version | sed -e  's/new_version=//')

git flow release start ${NEW_DBND_VERSION}
bumpversion $VERSION_TYPE
git flow release finish  ${NEW_DBND_VERSION}
git push --tags && git push && git checkout master && git push && git checkout develop
